version: '3.8'
services:
  db:
    image: postgres:16.2-bookworm
    environment:
      - POSTGRES_DB=brutus
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:secret@db/brutus
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=secret
      - PGDATABASE=brutus

volumes:
  postgres_data:
