DROP TABLE IF EXISTS message;

DROP TABLE IF EXISTS chat;

DROP TABLE IF EXISTS listing;

DROP TABLE IF EXISTS class_drop;

DROP TABLE IF EXISTS want;

DROP TABLE IF EXISTS class;

DROP TABLE IF EXISTS users;

DROP TYPE IF EXISTS WantType;
